/* eslint-disable no-shadow */
import Head from 'next/head';
import React, { useState } from 'react';
import axios from 'axios';

const Home = () => {
  const [file, setFile] = useState('');
  const [images, setImages] = useState([]);

  async function postImage({ picture }: { picture: string}) {
    const formData = new FormData();
    formData.append('picture', picture);

    const result = await axios.post('http://localhost:4000/images', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    return result.data;
  }

  const submit = async (event: any) => {
    event.preventDefault();
    const result = await postImage({ picture: file });
    // @ts-ignore
    setImages([result.image, ...images]);
  };

  const fileSelected = (event: any) => {
    const file = event.target.files[0];
    setFile(file);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={submit}>
        <input onChange={fileSelected} type="file" accept="image/*" />
        <button type="submit">Submit</button>
      </form>
    </div>
  );
};
export default Home;
