import Head from 'next/head';
import { useState } from 'react';
import { withApollo } from '../utils/withApollo';

const Home = () => {
  const [file, setFile] = useState('');
  const [title, setTitle] = useState('');
  const [images, setImages] = useState([]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  );
};
export default withApollo({ ssr: true })(Home);
